// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoEo5CFd4A_qyWlpnyBnaJ2ac_cKbOTRA',
    appId: '1:871986626469:web:6792493483ed0ddceff24c',
    messagingSenderId: '871986626469',
    projectId: 'smart-locker-84032',
    authDomain: 'smart-locker-84032.firebaseapp.com',
    databaseURL:
        'https://smart-locker-84032-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-locker-84032.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVm3UGuDyfo8gznmyadghbNwKdpL9Ofv0',
    appId: '1:871986626469:android:8ba70fea160db56aeff24c',
    messagingSenderId: '871986626469',
    projectId: 'smart-locker-84032',
    databaseURL:
        'https://smart-locker-84032-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-locker-84032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtPYcYaim_HUZ79Vh-KWk9_XMa6LkHFc',
    appId: '1:871986626469:ios:6551245f3a83bb01eff24c',
    messagingSenderId: '871986626469',
    projectId: 'smart-locker-84032',
    databaseURL:
        'https://smart-locker-84032-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-locker-84032.firebasestorage.app',
    iosBundleId: 'com.example.smartLockerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLtPYcYaim_HUZ79Vh-KWk9_XMa6LkHFc',
    appId: '1:871986626469:ios:6551245f3a83bb01eff24c',
    messagingSenderId: '871986626469',
    projectId: 'smart-locker-84032',
    databaseURL:
        'https://smart-locker-84032-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-locker-84032.firebasestorage.app',
    iosBundleId: 'com.example.smartLockerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoEo5CFd4A_qyWlpnyBnaJ2ac_cKbOTRA',
    appId: '1:871986626469:web:0623d2a0d3f7e68feff24c',
    messagingSenderId: '871986626469',
    projectId: 'smart-locker-84032',
    authDomain: 'smart-locker-84032.firebaseapp.com',
    databaseURL:
        'https://smart-locker-84032-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-locker-84032.firebasestorage.app',
  );
}
